### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by Porco-Rosso** [itzmeanjan/chanalyze#1]
Hi, I am interested in running the script, but get this error.
```
[+]chanalyze v0.1.1 - A simple WhatsApp Chat Analyzer 
[*]Working ...
Traceback (most recent call last): 
  File "./app.py", line 70, in main
    getConversationInitializers(chat),
  File "/root/wchat/chanalyze/util.py", line 386, in getConversationInitializers
    meanDelay = sum([i.elapsedTime for i in unique])//len(unique)
ZeroDivisionError: integer division or modulo by zero

[#]Success: 0.0000%
```

**Comment by itzmeanjan** [comment]
This issue has been resolved. 

Now `chanalyze` can be installed using

```bash
$ python3 -m pip install --user chanalyze 
```

:)
